config/routes.rb
IS376Api::Application.routes.draw do

	namespace :api, defaults: {format: 'json'} do
		namespace :v1 do
			devise_for :user, :token_authentication_key => 'authentication_key', controllers: {sessions: "api::v1::sessions", registrations: "api::v1::registrations"}
			resources :users, except: [:new, :edit]
			resources :friendships
			resources :commitments
			resources :surveys
		end
	end
	
	devise_scope :user do
		devise_for :user
		#get "/" => "devise/sessions#new", :as => :user_session
		match "log_out" => "devise/sessions#destroy", :as => "log_out"
		match "sign_up" => "devise/registrations#new", :as => "sign_up"
		
		root to: "devise/sessions#new"
	end
	
	resources :users
	resources :commitments
	resources :friendships
	resources :surveys
	
	match "/friendships/delete/:id" => "friendships#destroy", as: "delete_friendship"
	match "/friendships/update/:id" => "friendships#update", as: "update_friendship"	
	
	match "/commitments/delete/:id" => "commitments#destroy", as: "delete_commitment"
	match "/commitments/update/:id" => "commitments#update", as: "update_commitment"	

	match "/surveys/update/:id" => "surveys#update", as: "complete_survey"
	
	
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  attr_accessible :friend_id,:user_id, :friendship_status
	
	belongs_to :user
	belongs_to :friend, :class_name => "User", :foreign_key => :friend_id
	
	#Status variables
	ACCEPTED = 2
	REQUESTED = 1
	PENDING = 0
	
	#methods for finding friendships at specific
	#stages in the friendship process
	scope :accepted_friendships, where(friendship_status: ACCEPTED)
	scope :friendships_requested, where(friendship_status: REQUESTED)
	scope :friendships_pending, where(friendship_status: PENDING)
	
	before_save :is_lonely?
	
	def friendship_status_string
		if friendship_status == 0
			"Pending"
		elsif friendship_status == 1
			"Requested"
		elsif friendship_status == 2
			"Accepted"
		else
			"null"
		end
	end
	
	#prevents users from being friends with themselves
	def is_lonely?
		if self.friend_id == self.user_id
			false
		end
	end
	
	def accept
		Friendship.accept(user_id, friend_id)
	end
	
	def break_up
		Friendship.break_up(user_id, friend_id)
	end
	
	class << self
	
	
		def break_up(user, friend)
			transaction do
				destroy(link(user, friend))
				destroy(link(friend, user))
			end
		end	
		
		def link(user, friend)
			find_by_user_id_and_friend_id(user, friend)
		end
	
		def connect(user, friend)
			transaction do
				request(user, friend)
				accept(friend, user)
			end
		end
		
		def request(user, friend)
			transaction do
				create(:user_id => user.id, :friend_id => friend.id, :friendship_status => PENDING)
				create(:user_id => friend.id, :friend_id => user.id, :friendship_status => REQUESTED)
			end
			true
		end
		
		def accept(user, friend)
			transaction do 
				add_one_side(user, friend)
				add_one_side(friend, user)
			end
		end

		def add_one_side(user, friend)
			link = link(user, friend)  
			link.update_attributes!(:friendship_status => ACCEPTED)
		end
	end
end

app/controllers/api/v1/friendships_controller.rb
class Api::V1::FriendshipsController < Api::V1::ApiController
	before_filter :validate_authentication_token!
	
  def create
		@new_friend = User.find(params[:requested_user_id])
		if Friendship.request(current_user, @new_friend)
			@friendships = Friendship.where(user_id: current_user.id , friend_id: @new_friend.id)
			render :json => {:message => ":Friend request sent to #{@new_friend.user_name}.", :current_user => current_user.user_name}, :status => 200
		else
			render :json => {:message => 'Unable to send friend request.'}, :status => 200
		end
	end
	
	def update
		@friendship = Friendship.find(params[:id])
    if @friendship.accept
      render :json => {:message => 'Friend Added.'}, :status => 200
    else
      render :json => {:message => 'Could not add friend.'}, :status => 400
    end
	end
	
	def destroy
		@friendship = Friendship.find(params[:id])
		if @friendship.break_up
			render :json => {:message => 'Friendship successfully removed.'}, :status => 200
		else
			render :json => {:message => 'Could not remove friend.'}, :status => 400
		end
		#add remove
	end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

	def index
		@friendships = current_user.friendships
		@friends = current_user.friends
    @query = params[:search]
    @results = User.search(@query, current_user)
		
		@pending_friendships = current_user.friendships.friendships_pending
		@requested_friendships = current_user.friendships.friendships_requested
		@current_friendships = current_user.friendships.accepted_friendships

	end

	def show
	
	end

	def new
		@friendship = Friendship.new
	end
	
  def create
		@new_friend = User.find(params[:user_id])

		if Friendship.request(current_user, @new_friend)
			flash[:notice] = "Friend request sent"
			redirect_to friendships_path
		else
			flash[:error] = "Unable to send friend request." #Add more specific error message
			redirect_to friendships_path
		end
	end
	
	def update
		@friendship = Friendship.find(params[:id])
		if @friendship.accept
			redirect_to user_path(current_user)
			#render :json => {:message => 'Friend Added.'}, :status => 200
		else
			#error
		end
	end
	
	def destroy
		@friendship = Friendship.find(params[:id])
		@friend_id = @friendship.friend.id
		if Friendship.break_up(current_user.id, @friend_id)
			redirect_to user_path(current_user)
		else
			redirect_to friendships_path
		end
	end
end

app/views/friendships/index.html.erb
<div class="container main-content">
  <div class="row">

    <div class="span4">
      <div class="row">
        <div class="well">
          <h4 class="highlight-header text-center">Your Friends</h4>
          <hr>
          <ol>
            <% if @current_friendships.empty? %>
                <i>You have no friends :( </i>
            <% else %>
                <% @current_friendships.each do |friendship| %>
										<% friend = friendship.friend %>
                    <%= friend.email %>
                    <%= friend.user_name %>
                    <%= friendship.friendship_status_string %>
                    <% if friendship.friendship_status == 0 %>
                        <span class="highlight"><i>Be Patient</i></span>
                    <% elsif friendship.friendship_status == 1 %>
                        <%= button_to "Accept Friend", update_friendship_path(friendship), method: :put %>
                    <% elsif friendship.friendship_status == 2 %>
                        <%= button_to "Remove Friend", delete_friendship_path(friendship), method: :delete %>
                    <% end %>
                <% end %>
            <% end %>
          </ol>
        </div>


        <div class="well">
          <h4 class="highlight-header text-center">Pending Friend Requests</h4>
          <hr>
          <ol>
            <% if @requested_friendships.empty? %>
                <i>You have no friend requests :( </i>
            <% else %>
                <% @requested_friendships.each do |friendship| %>
										<% friend = friendship.friend %>
                    <%= friend.email %>
                    <%= friend.user_name %>
                    <%= friendship.friendship_status_string %>
                    <% if friendship.friendship_status == 0 %>
                        <span class="highlight"><i>Be Patient</i></span>
                    <% elsif friendship.friendship_status == 1 %>
                        <%= button_to "Accept Friend", update_friendship_path(friendship), method: :put %>
                    <% elsif friendship.friendship_status == 2 %>
                        <%= button_to "Remove Friend", delete_friendship_path(friendship), method: :delete %>
                    <% end %>
                <% end %>
            <% end %>
          </ol>
        </div>
      </div>
    </div>

    <div class="span8" id="friend-search-body" ng-controller="Graph">
      <div class="row">
        <div class="span9">
          <h3 class="highlight-header">Search Users</h3>

          <p>
            <%= form_tag 'friendships', :method => 'get' do %>
                <%= text_field_tag :search, params[:search], class: 'search-text' %>
                <%= submit_tag "Search", :name => nil, class: 'btn btn-primary' %>
            <% end %>
          </p>
          <hr>
        </div>
      </div>


      <div class="row">
        <div class="span9">
          <div class="user-search-results-body">
            <% if @query.blank? %>
                <h4 class="highlight-header text-center">All Users</h4>
            <% else %>
                <h4 class="highlight-header text-center">Results for "<%= @query %>"</h4>
            <% end %>

            <ul class="media-list result-list">
              <% for user in @results %>
                  <% profUrl = "users/" + user.id.to_s %>
                  <% relation = Friendship.where(friend_id: user.id, user_id: current_user).first %>
                  <% otherRelation = Friendship.where(friend_id: current_user, user_id: user.id).first %>
                  <li class="media">
                    <a class="pull-left" href="<%= profUrl %>">
                      <img class="media-object" src="<%= avatar_url(user) %>">
                    </a>

                    <div class="media-body">
                      <h4><a href="<%= profUrl %>"><%= user.user_name %></a></h4>
                      <h5>Score: <%= user.r_c_score %></h5>
                      <div class="btn-area">
                        <% if relation.blank? %>
                            <button onclick="friendRequest(<%= user.id %>);" type="button" class="btn btn-primary">Add</button>
                        <% elsif relation.friendship_status_string == 'Accepted' %>
                            <button onclick="deleteFriendship(<%= relation.id %>);" type="button" class="btn btn-danger">Remove</button>
                        <% elsif relation.friendship_status_string == 'Pending' %>
                            <button onclick="deleteFriendship(<%= relation.id %>);" type="button" class="btn btn-warning">Cancel</button>
                        <% elsif relation.friendship_status_string == 'Requested' %>
                            <button onclick="updateFriendship(<%= relation.id %>);" type="button" class="btn btn-success">Accept</button>
                            <button onclick="deleteFriendship(<%= relation.id %>);" type="button" class="btn btn-default">Reject</button>
                        <% end %>
                      </div>
                    </div>
                  </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
    var AUTH_TOKEN = "<%=current_user.authentication_token%>";
    var friendRequest = function(uid) {
        $.ajax({
            type: "POST",
            url: "/api/v1/friendships",
            data: { authentication_token: AUTH_TOKEN, requested_user_id: uid }
        })
                .done(function( msg ) {
                    location.reload();
                });
    }
    var updateFriendship = function(fid) {
        $.ajax({
            type: "PUT",
            url: "/api/v1/friendships/" + fid,
            data: { authentication_token: AUTH_TOKEN}
        })
                .done(function( msg ) {
                    location.reload();
                });
    }
    var deleteFriendship = function(fid) {
        $.ajax({
            type: "DELETE",
            url: "/api/v1/friendships/" + fid,
            data: { authentication_token: AUTH_TOKEN}
        })
                .done(function( msg ) {
                    location.reload();
                });
    }
</script>