config/routes.rb
IS376Api::Application.routes.draw do

	namespace :api, defaults: {format: 'json'} do
		namespace :v1 do
			devise_for :user, :token_authentication_key => 'authentication_key', controllers: {sessions: "api::v1::sessions", registrations: "api::v1::registrations"}
			resources :users, except: [:new, :edit]
			resources :friendships
			resources :commitments
			resources :surveys
		end
	end
	
	devise_scope :user do
		devise_for :user
		#get "/" => "devise/sessions#new", :as => :user_session
		match "log_out" => "devise/sessions#destroy", :as => "log_out"
		match "sign_up" => "devise/registrations#new", :as => "sign_up"
		
		root to: "devise/sessions#new"
	end
	
	resources :users
	resources :commitments
	resources :friendships
	resources :surveys
	
	match "/friendships/delete/:id" => "friendships#destroy", as: "delete_friendship"
	match "/friendships/update/:id" => "friendships#update", as: "update_friendship"	
	
	match "/commitments/delete/:id" => "commitments#destroy", as: "delete_commitment"
	match "/commitments/update/:id" => "commitments#update", as: "update_commitment"	

	match "/surveys/update/:id" => "surveys#update", as: "complete_survey"
	
	
end

app/views/layouts/_footer.html.erb
<div id="footer">
	<div class="container">
		<p class="muted credit">A site by Team 3 </p>
	</div>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="navbar-inner">
			<div class="container">
				<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="brand" href="#">Relation Capital</a>
				<div class="nav-collapse collapse">
					<ul class="nav">
						<li><%= link_to(image_tag("home.png", class:"nav-image", size: "25x25"), root_url) %></a></li>
						<li><a href="#friends"><%= image_tag("commitment.png", class:"nav-image", size: "25x25") %></a></li>
						<li><%= link_to(image_tag("friend.png", class:"nav-image", size: "25x25"),friendships_path, method: "get") %></li>
						<li><a href="#settings"><%= image_tag("setting.png", class:"nav-image", size: "25x25") %></a></li>
					</ul>
					<div class="navbar-form pull-right">
						<<%= link_to("log out", log_out_path , class: "span1 nav-links-auth") %>
						<%= link_to("Profile", user_path(current_user) , class: "span1 nav-links-auth") %>
           </div>
				</div><!--/.nav-collapse -->
			</div>
		</div>
	</div>

app/views/layouts/_main_dashboard.html.erb
<div class="row">

  <div class="span4">
    <div class="row">
      <div class="well">
        <h4 class="highlight-header text-center"><%= @user.user_name %>'s Dashboard</h4>
        <hr>
        <center><%= image_tag(avatar_url(@user), size: "150x150") %></center>
        <hr>
        <p class="rcScoreElement">Relation Capital Score:</p>

        <h2 id="rcScore" class="rcScoreElement"><%= @user.r_c_score %></h2>

        <p class="rcScoreElement"><%= link_to("More Info", "#") %></p>
        <hr>
        <% if current_user !=  @user %>
            <%= link_to("Send " + @user.user_name + " a request", new_commitment_path) %>
        <% end %>
      </div>
    </div>

    <%= render "layouts/ongoing_commitments" %>
    <%= render "layouts/ongoing_requests" %>


  </div>

  <div class="span8" id="graph-body" ng-controller="Graph">
    <div class="row">
      <div class="span9">
        <h3 class="highlight-header">Commitments </h3>

        <h4 class="highlight-header"><span>  <a class="approvedCommit" href="#">Approved</a> |</span>
        <span><a class="fulfilledCommit" href="#">Fulfilled</a> |</span>
        <span><a class="pendingCommit" href="#">Pending</a> </span>   </h4>
        <hr>

        <div class="user-graph">
        </div>
        <hr>
        <h3 class="highlight-header">Additional Info</h3>

        <p>something something shome</p>
      </div>
    </div>
  </div>
  <!-- MOVE TO OWN LIBRARY SECTION -->
  <script>
      $('document').ready(function () {
          var AUTH_TOKEN = "<%=current_user.authentication_token%>";
          var uid = '' + <%= @user.id %>;
          $.getJSON('/api/v1/users/' + uid, {authentication_token: AUTH_TOKEN}, function (json) {
              $('.fulfilledCommit').addClass('active');
              new UserGraph(json, $('.user-graph'), 4, 'Fulfilled');
              new GraphBodyHandler(json, $('#graph-body'));
          });
      });
  </script>
</div>

app/views/layouts/_ongoing_commitments.html.erb
<div class="row">
	<div class="well">
		<h4 class="highlight-header text-center">Ongoing Commitments</h4><hr>
		<ol>
			<% if @commitments.empty? or @commitments.count == 0 %>
				<p>You have no ongoing commitments.</p>
			<% else %>
				<% @commitments.each do |commitment| %>
				<li>
					<b><%= link_to(commitment.name, commitment) %></b><hr>
					<b>Description:</b> <%= commitment.description %><br>
					<b>Status: <%= commitment.status_string %></b>
					<% if commitment.status == 0 %>
						<%= button_to("Accept Commitment", update_commitment_path(commitment), method: :put, class: "btn btn-success") %>
					<% elsif commitment.status == 2%>
						<%= button_to("Submit for Approval", update_commitment_path(commitment), method: :put, class: "btn btn-success") %>
					<% elsif commitment.status == 3%>
							<p><i>Submitted, waiting for approval.</i></p>
					<% elsif commitment.status == 5%>
						<p><i>Your commitment has been approved!</i></p>
					<% else %>
					<% end %>
				</li>
			    <% end %>
		    <% end %>
		</ol>
		<hr>
	</div>
</div>

app/views/layouts/_ongoing_requests.html.erb
<div class="row">
  <div class="well">
    <h4 class="highlight-header text-center">Ongoing Requests</h4><hr>
    <ol>
      <% if @requests.empty? %>
          <p>You have no ongoing requests.</p>
      <% else %>
          <% @requests.each do |commitment| %>
              <li>
                <b><%= link_to(commitment.name, commitment) %></b>
                <div class="well">
                  <b>Description:</b> <%= commitment.description %><br>
                  <b>Status: <%= commitment.status_string %></b>
                  <% if commitment.status == 1 %>
                      <p><i>Pending</i></p>
                  <% elsif commitment.status == 2%>
                      <p><i>Commitment ongoing</i></p>
                  <% elsif commitment.status == 3%>
                      <p><i>Verify Commitment completion :</i></p>
                      <%= button_to("Verify", update_commitment_path(commitment), method: :put) %>
                  <% elsif commitment.status == 5%>
                      <p><i>This commitment has been Completed and approved!</i></p>                  
                      <p><i><%= button_to("Complete Survey", complete_survey_path(commitment.survey), method: :put, class: "btn btn-success") %></i></p>                  
									<% elsif commitment.status == 6%>
                      <p><i>This commitment has been Completed and approved! Survey Compleete</i></p>
                  <% else %>
                  <% end %>
                </div>
              </li>
          <% end %>
      <% end %>
    </ol>
    <hr>
    <% if current_user ==  @user %>
        <%= link_to("Create commitment", new_commitment_path) %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="relationCapitalApp">
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>RelationCapital</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrap">
	<% if user_signed_in? %>
		<%= render "layouts/header"%>
	<% end %>
	<%= yield %>
	
	
	<div id="push"></div>
</div>

<%= render "layouts/footer" %>
</body>
</html>